### ISSUE TITLE
[Bug] Text becomes blurry when run with Optifine

### ISSUE THREAD

**Issue by anarisis** [InnovativeOnlineIndustries/Emojiful#36]
## Issue
When the chat is opened while Emojiful and Optifine are loaded, all text within the game (and occasionally other textures, though this occurs less reliably) becomes blurred as if loaded at a low resolution and upscaled.

I have gone into greater detail in the Optifine report of this issue: https://github.com/sp614x/optifine/issues/6570

**Comment by mysticdrew** [comment]
@Buuz135 
I encountered this issue and other texture issues with optifine. My solution was to remove all BufferedImages and use the Minecraft SimpleTexture, DynamicTextures and my own implementation using NativeImage in Journeymap. 

It was a huge pain and required a lot of testing, since the stbimage textures sit in native memory, not jvm memory. But, it is better for all getting rid of AWT, as it does not work well on macs and is pretty slow compared to stbimage. STB_Image used by lwjgl is much faster and more memory efficient. 
Feel free to hit me up in the Journeymap discord if you need any assistance.

**Comment by yuvalyly** [comment]
Any updates or workarounds for this issue?

**Comment by mysticdrew** [comment]
> Any updates or workarounds for this issue?

remove optifine

**Comment by yuvalyly** [comment]
That's not a solution. I need a performance mod for this pack and Rubidium isn't compatible with one of the other mods (crash on startup), and causes rendering issues with another.

**Comment by mysticdrew** [comment]
sounds like a you problem. 
That is the solution, optifine breaks all kinds of crap, deal with it or remove it.

**Comment by yuvalyly** [comment]
Do you have any suggestion for a replacement mod? Like I said earlier, Rubidium breaks even more things than Optifine. (Performance mods in general tend to break things)

Also, what's the point of this bug reporting forum if you are not going to even try to fix it?

**Comment by Felix14-v2** [comment]
> Like I said earlier, Rubidium breaks even more things

Sodium ¯\\\_(ツ)\_/¯
CaffeineMC is not responsible for the failure of its unofficial ports on Forge.

> Performance mods in general tend to break things

If you mean mods like Optifine, then yes. Now Sodium is compatible with the vast majority of mods, and its open source makes it easy to fix incompatibilities.

> Also, what's the point of this bug reporting forum if you are not going to even try to fix it?

It is impossible to fix compatibility with a closed source mod ¯\\\_(-_-)\_/¯

**Comment by stepan14041999** [comment]
Need to apply this fix. Tested with optifine. Works fine
![image](https://github.com/InnovativeOnlineIndustries/Emojiful/assets/24523947/ce933358-681a-46d0-adbd-1eac419389d7)
