### ISSUE TITLE
Conflicts with styledchat

### ISSUE THREAD

**Issue by FederAndInk** [InnovativeOnlineIndustries/Emojiful#70]
`:)` is being transformed into `:slightly_smiling_face:` that is interpreted as markdown by [styledchat](https://github.com/Patbox/StyledChat) (it puts *smiling* in italic). However, it works with `:(` spawning the emoji and is not modified by styledchat:

![Screenshot_20230131_010756](https://user-images.githubusercontent.com/24270152/215625034-46e233b5-a546-4a20-bd41-b364dbf23f41.png)

![Screenshot_20230131_010749](https://user-images.githubusercontent.com/24270152/215625025-ceaba83b-53f5-4d1f-988f-f37a3a33e654.png)

- fabric with MC 1.19.2
- emojiful 4.0.4
- styled chat 2.0.2

**Comment by Witixin1512** [comment]
I'm not sure what emojiful can even do in this context, because from what I can see, Styled Chat is unconditionally and always adding the italic style to all substrings that have `_` in between, as well as stripping the characters from the message. 

I haven't debugged it extensively, but I cannot see any option for StyledChat to disable italic checking...

**Comment by FederAndInk** [comment]
Thanks for the answer, what's weird though is that it's working with `:(` or `:D` it correctly inserts the emoji and isn't transformed by styled chat

**Comment by Witixin1512** [comment]
Yes? Why would you expect that to transform the emoji by styled chat?
Styled Chat replaces `_hello_` with _hello_, like Github or Markdown formatting does. The problem is that it does that before Emojiful sees the emoji, so whenever Emoji sees the message it has been turned into: `:slightly(smiling)face:` where `smiling` is in italic.

**Comment by FederAndInk** [comment]
I mean, this is not working (see the preview of styled chat above and what I typed under):
![Screenshot_20230131_123805](https://user-images.githubusercontent.com/24270152/215749938-692fe665-4a08-4f58-8078-a4c2640c3f73.png)

and this is working:
![Screenshot_20230131_123906](https://user-images.githubusercontent.com/24270152/215750137-9bf99fcb-8be2-4e11-870a-6b2f643d4c7a.png)

in both cases I used `:)` or `:(` but the former is parsed by styled chat and the later not

**Comment by FederAndInk** [comment]
ok sorry, I thought `:(` was `:slightly_frowning_face:`

**Comment by Witixin1512** [comment]
That happens because the top one has a substring surrounded by _, which causes StyledChat to replace it with italic.

**Comment by FederAndInk** [comment]
> ok sorry, I thought `:(` was `:slightly_frowning_face:`

I know markdown rules ^^
just didn't realized `:(` wasn't `:slightly_frowning_face:`

**Comment by Patbox** [comment]
Btw, this was fixed a while ago, feel free to close

**Comment by Buuz135** [comment]
Thanks for letting me know
