### ISSUE TITLE
Trojan warning from Emojiful-forge-1.20.1-4.2.0

### ISSUE THREAD

**Issue by rastrof** [InnovativeOnlineIndustries/Emojiful#87]
Emojiful as distributed with the FTB Direwolf 1.20 modpack throws a Trojan warning in the latest version of Bitdefender:

Emojiful-Forge-1.20.1-4.2.0.jar has been detected as infected with Java.Trojan.GenericGBA.32839. Bitdefender deleted this item, your devic is safe.

As of the time of writing the FTB Direwolf 1.20 modpack is on pack-version 1.6.0

**Comment by Medivha** [comment]
same for me. same pack was opening the update available to update 1.7.0 from 1.6.0 and Bitdefender was giving me 
`
The file G:\gamez\pc\minecraft_and_stuff\ftb\instances\e16d85ab-0d78-4b6b-b474-3d043b3d0f23\mods\Emojiful-Forge-1.20.1-4.2.0.jar has been detected as infected with Java.Trojan.GenericGBA.32839. Bitdefender deleted this item, your device is safe.`

and
`
The file G:\gamez\pc\minecraft_and_stuff\ftb\instances\e16d85ab-0d78-4b6b-b474-3d043b3d0f23\mods\Emojiful-Forge-1.20.1-4.2.0.jar=>com/esotericsoftware/yamlbeans/emitter/Emitter.class is infected with Java.Trojan.GenericGBA.32839 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean`

and another 2 for the .localcache

i assume a false postive because bitdefender change something. Because i just don't even downloaded the update yet(assuming that the ftb app doesn't download it beforehand, but it also mentions the mod folder in the actual instance so it can't be)

**Comment by Buuz135** [comment]
It probably a false positive as it wasn't doing it before, I will keep an eye for changes

**Comment by Buuz135** [comment]
I'm closing this as its shown now as clean

![](https://i.imgur.com/Re1KWM6.png)
